import React, { Component } from 'react';
import './Recommend.css'
class Recommend extends Component {
    constructor(props) {
        super(props);
        this.state = {
            // 这数据来源于2019.12.16日的网易云音乐商城API
            RecommendData: {
                "count": 8,
                "hasMore": false,
                "hotProduct": [
                    {
                        "db_create_time": 1576484502596,
                        "id": 10004,
                        "names": "伯朗 i12触控真无线蓝牙耳机蓝牙5.0苹果安卓通用",
                        "price": null,
                        "productId": 11728001,
                        "resourceUrl": null,
                        "orderWeight": 1,
                        "products": {
                            "stock": 1994,
                            "saleNum": 0,
                            "sumMoney": null,
                            "skus": null,
                            "discount": null,
                            "pickUp": false,
                            "picIds": [
                                "109951164202388691",
                                "109951164143698270",
                                "109951164086508329",
                                "109951164087881382",
                                "109951164094133649",
                                "109951164086508406",
                                "109951164094128831",
                                "109951164094127414"
                            ],
                            "couponLabelDesc": null,
                            "couponLabelFlag": 0,
                            "label": null,
                            "category1": 101000,
                            "drawTime": 0,
                            "pubTime": 1558342503208,
                            "createTime": 1558275816562,
                            "priceType": 1,
                            "levelLimit": 0,
                            "vipLimit": false,
                            "allowDupBuy": true,
                            "extInfo": {
                                "albumId": 0,
                                "songId": 0,
                                "goodVipType": 11,
                                "quotaOfOrder": 0,
                                "extProductId": 0,
                                "extProductStatus": 0,
                                "extShelfStatus": 0,
                                "concertId": 0,
                                "buysingle": false,
                                "showStartProId": 0,
                                "needMessage": 0,
                                "message": "",
                                "preSale": 1,
                                "defaultMessage": "",
                                "albumSaleDisplayType": 0,
                                "restrict": 1,
                                "giftSet": 1
                            },
                            "specialType": 0,
                            "shopId": 84000,
                            "exchangeType": 0,
                            "useVipPrice": false,
                            "statistics": 6,
                            "picUrls": [
                                "http://p4.music.126.net/bjuML9O6zMvw22miFq3sUg==/109951164202388691.jpg",
                                "http://p4.music.126.net/orvie8SodGTTU4W3DqaSvw==/109951164143698270.jpg",
                                "http://p4.music.126.net/W25TGBy0jHeRHALk9DRa1w==/109951164086508329.jpg",
                                "http://p3.music.126.net/CtwNkxtriupQLoIMVSz88A==/109951164087881382.jpg",
                                "http://p3.music.126.net/U0Y1CGpHbV-0jlqgdcX4SQ==/109951164094133649.jpg",
                                "http://p3.music.126.net/YkTEnVjpChY6YswU_K2v3w==/109951164086508406.jpg",
                                "http://p4.music.126.net/h_LZ7v-r-e5XpdGGcYUJOQ==/109951164094128831.jpg",
                                "http://p4.music.126.net/Jgc770AJFctwFSO63Qe7KA==/109951164094127414.jpg"
                            ],
                            "coverUrl": "http://p3.music.126.net/bjuML9O6zMvw22miFq3sUg==/109951164202388691.jpg",
                            "performanceTime": 0,
                            "coverIdStr": "109951164202388691",
                            "category2": 1005000,
                            "suggestWord": "【赠送硅胶保护套+登山扣】智能触控；20小时长效续航；自动配对；蓝牙5.0；双耳通话；",
                            "brandName": "伯朗",
                            "alterStock": 0,
                            "iap": false,
                            "tags": [
                                "特价"
                            ],
                            "display": 0,
                            "status": 0,
                            "name": "伯朗 i12触控真无线蓝牙耳机蓝牙5.0苹果安卓通用",
                            "id": 11728001,
                            "type": 2,
                            "minPrice": 129,
                            "originalCost": 199,
                            "maxPrice": 129,
                            "alg": "featured"
                        },
                        "db_update_time": 1576469552000
                    },
                    {
                        "db_create_time": 1576484502596,
                        "id": 13009,
                        "names": "kinbor 音乐的力量套装 DTB6550",
                        "price": null,
                        "productId": 21748602,
                        "resourceUrl": null,
                        "orderWeight": 2,
                        "products": {
                            "stock": 102,
                            "saleNum": 0,
                            "sumMoney": null,
                            "skus": null,
                            "discount": null,
                            "pickUp": false,
                            "picIds": [
                                "109951164389370205",
                                "109951164389371286",
                                "109951164389379001",
                                "109951164389366496",
                                "109951164389378551",
                                "109951164389368935"
                            ],
                            "couponLabelDesc": null,
                            "couponLabelFlag": 0,
                            "label": "",
                            "category1": 2021000,
                            "drawTime": 0,
                            "pubTime": 1569728506994,
                            "createTime": 1569564905005,
                            "priceType": 1,
                            "levelLimit": 0,
                            "vipLimit": false,
                            "allowDupBuy": true,
                            "extInfo": {
                                "albumId": 0,
                                "songId": 0,
                                "goodVipType": 0,
                                "quotaOfOrder": 0,
                                "extProductId": 0,
                                "extProductStatus": 0,
                                "extShelfStatus": 0,
                                "concertId": 0,
                                "buysingle": false,
                                "showStartProId": 0,
                                "needMessage": 0,
                                "message": "",
                                "preSale": 1,
                                "defaultMessage": "",
                                "tax": "0.13",
                                "albumSaleDisplayType": 0,
                                "restrict": 1,
                                "giftSet": 1
                            },
                            "specialType": 0,
                            "shopId": 104000,
                            "exchangeType": 0,
                            "useVipPrice": false,
                            "statistics": 0,
                            "picUrls": [
                                "http://p4.music.126.net/_M9C7kRjeqKHYILvsmD2eQ==/109951164389370205.jpg",
                                "http://p3.music.126.net/beiczpZk_x4tNqK2RNqoEg==/109951164389371286.jpg",
                                "http://p4.music.126.net/yCVO1L-m82talhNw98fPjQ==/109951164389379001.jpg",
                                "http://p3.music.126.net/f34aOf3TlJ9YeHPfgsjaeA==/109951164389366496.jpg",
                                "http://p4.music.126.net/hdlvg25okclUSTrm03i9gg==/109951164389378551.jpg",
                                "http://p3.music.126.net/fqOexitiL8Tv0oDBqAGKIg==/109951164389368935.jpg"
                            ],
                            "coverUrl": "http://p3.music.126.net/beiczpZk_x4tNqK2RNqoEg==/109951164389371286.jpg",
                            "performanceTime": 0,
                            "coverIdStr": "109951164389371286",
                            "category2": 2024000,
                            "suggestWord": "",
                            "brandName": "kinbor",
                            "alterStock": 0,
                            "iap": false,
                            "tags": [
                                "特价",
                                "包邮"
                            ],
                            "display": 0,
                            "status": 0,
                            "name": "kinbor 音乐的力量套装 DTB6550",
                            "id": 21748602,
                            "type": 2,
                            "minPrice": 39,
                            "originalCost": 138,
                            "maxPrice": 39,
                            "alg": "featured"
                        },
                        "db_update_time": 1576469552000
                    },
                    {
                        "db_create_time": 1576484502596,
                        "id": 10006,
                        "names": "网易云音乐青春系列印花羽绒服 NO.1",
                        "price": null,
                        "productId": 18104003,
                        "resourceUrl": null,
                        "orderWeight": 3,
                        "products": {
                            "stock": 665,
                            "saleNum": 0,
                            "sumMoney": null,
                            "skus": null,
                            "discount": null,
                            "pickUp": false,
                            "picIds": [
                                "109951164386108151",
                                "109951164386100474",
                                "109951164376468302",
                                "109951164376474141",
                                "109951164376469299",
                                "109951164376469785",
                                "109951164376475626"
                            ],
                            "couponLabelDesc": null,
                            "couponLabelFlag": 0,
                            "label": "",
                            "category1": 1002000,
                            "drawTime": 0,
                            "pubTime": 1569407485877,
                            "createTime": 1568989992644,
                            "priceType": 1,
                            "levelLimit": 0,
                            "vipLimit": false,
                            "allowDupBuy": true,
                            "extInfo": {
                                "albumId": 0,
                                "songId": 0,
                                "goodVipType": 0,
                                "quotaOfOrder": 0,
                                "extProductId": 0,
                                "extProductStatus": 0,
                                "extShelfStatus": 0,
                                "concertId": 0,
                                "buysingle": false,
                                "showStartProId": 0,
                                "needMessage": 0,
                                "message": "",
                                "preSale": 1,
                                "albumSaleDisplayType": 0,
                                "restrict": 1,
                                "giftSet": 1
                            },
                            "specialType": 0,
                            "shopId": 0,
                            "exchangeType": 0,
                            "useVipPrice": false,
                            "statistics": 0,
                            "picUrls": [
                                "http://p4.music.126.net/bkBHYFMjYuufyULKoSpu-w==/109951164386108151.jpg",
                                "http://p3.music.126.net/syOVDu8kNNRqEl-KADTxbg==/109951164386100474.jpg",
                                "http://p3.music.126.net/NWcC8E3pJuYxJuD9dTzE_g==/109951164376468302.jpg",
                                "http://p4.music.126.net/obNFZkey6cONqODPOzuDIg==/109951164376474141.jpg",
                                "http://p4.music.126.net/3BK0bqbNngGBXF0E36OUtA==/109951164376469299.jpg",
                                "http://p4.music.126.net/-9cp8ZbfzXih8WI_C9hM_g==/109951164376469785.jpg",
                                "http://p3.music.126.net/FGtpUQabe2ILoEjZke_H_Q==/109951164376475626.jpg"
                            ],
                            "coverUrl": "http://p4.music.126.net/bkBHYFMjYuufyULKoSpu-w==/109951164386108151.jpg",
                            "performanceTime": 0,
                            "coverIdStr": "109951164386108151",
                            "category2": 1008000,
                            "suggestWord": "",
                            "brandName": "网易云音乐",
                            "alterStock": 0,
                            "iap": false,
                            "tags": [
                                "特价"
                            ],
                            "display": 0,
                            "status": 0,
                            "name": "网易云音乐青春系列印花羽绒服 NO.1",
                            "id": 18104003,
                            "type": 2,
                            "minPrice": 369,
                            "originalCost": 699,
                            "maxPrice": 369,
                            "alg": "featured"
                        },
                        "db_update_time": 1576469552000
                    },
                    {
                        "db_create_time": 1576484502596,
                        "id": 10008,
                        "names": "网易云音乐联名款真无线蓝牙耳机TWS1",
                        "price": null,
                        "productId": 17859000,
                        "resourceUrl": null,
                        "orderWeight": 4,
                        "products": {
                            "stock": 2807,
                            "saleNum": 0,
                            "sumMoney": null,
                            "skus": null,
                            "discount": null,
                            "pickUp": false,
                            "picIds": [
                                "109951164310449986",
                                "109951164143642202",
                                "109951164143636993",
                                "109951164143644694",
                                "109951164143637462"
                            ],
                            "couponLabelDesc": null,
                            "couponLabelFlag": 0,
                            "label": null,
                            "category1": 101000,
                            "drawTime": 0,
                            "pubTime": 1560667298559,
                            "createTime": 1560393260915,
                            "priceType": 1,
                            "levelLimit": 0,
                            "vipLimit": false,
                            "allowDupBuy": true,
                            "extInfo": {
                                "albumId": 0,
                                "songId": 0,
                                "goodVipType": 0,
                                "quotaOfOrder": 0,
                                "extProductId": 0,
                                "extProductStatus": 0,
                                "extShelfStatus": 0,
                                "concertId": 0,
                                "buysingle": false,
                                "showStartProId": 0,
                                "needMessage": 0,
                                "message": "",
                                "preSale": 1,
                                "albumSaleDisplayType": 0,
                                "restrict": 1,
                                "giftSet": 1
                            },
                            "specialType": 0,
                            "shopId": 0,
                            "exchangeType": 0,
                            "useVipPrice": false,
                            "statistics": 0,
                            "picUrls": [
                                "http://p3.music.126.net/SuPD2sAWzilVM2OpcwYr6A==/109951164310449986.jpg",
                                "http://p4.music.126.net/OrsjFNFlDOJq32aAeVeTYA==/109951164143642202.jpg",
                                "http://p3.music.126.net/UjkFFpTMCYCNtDh_VBRcBA==/109951164143636993.jpg",
                                "http://p3.music.126.net/ysz5YMQS0zktIgzZ2exsIA==/109951164143644694.jpg",
                                "http://p4.music.126.net/MpS6kMSbeU7GTWPIRZ7dUg==/109951164143637462.jpg"
                            ],
                            "coverUrl": "http://p3.music.126.net/SuPD2sAWzilVM2OpcwYr6A==/109951164310449986.jpg",
                            "performanceTime": 0,
                            "coverIdStr": "109951164310449986",
                            "category2": 1005000,
                            "suggestWord": "【漫步者&云音乐联名】32小时长效续航；蓝牙5.0高通芯片，aptX无损解码；生物振膜；触控操作；",
                            "brandName": "网易云音乐",
                            "alterStock": 0,
                            "iap": false,
                            "tags": [],
                            "display": 0,
                            "status": 0,
                            "name": "网易云音乐联名款真无线蓝牙耳机TWS1",
                            "id": 17859000,
                            "type": 2,
                            "minPrice": 298,
                            "originalCost": 298,
                            "maxPrice": 298,
                            "alg": "featured"
                        },
                        "db_update_time": 1576469552000
                    },
                    {
                        "db_create_time": 1576484502596,
                        "id": 13001,
                        "names": "【新品预售12月17日发货】网易云音乐易系列17音卡林巴拇指琴 二色可选",
                        "price": null,
                        "productId": 21832613,
                        "resourceUrl": null,
                        "orderWeight": 5,
                        "products": {
                            "stock": 173,
                            "saleNum": 0,
                            "sumMoney": null,
                            "skus": null,
                            "discount": null,
                            "pickUp": false,
                            "picIds": [
                                "109951164540945896",
                                "109951164540963201",
                                "109951164540960499",
                                "109951164540951818",
                                "109951164540958095",
                                "109951164540962309",
                                "109951164540965806",
                                "109951164552707706"
                            ],
                            "couponLabelDesc": "用券减120",
                            "couponLabelFlag": 2,
                            "label": null,
                            "category1": 1008001,
                            "drawTime": 0,
                            "pubTime": 1575968463383,
                            "createTime": 1575105132186,
                            "priceType": 1,
                            "levelLimit": 0,
                            "vipLimit": false,
                            "allowDupBuy": true,
                            "extInfo": {
                                "albumId": 0,
                                "songId": 0,
                                "goodVipType": 11,
                                "quotaOfOrder": 0,
                                "extProductId": 0,
                                "extProductStatus": 0,
                                "extShelfStatus": 0,
                                "concertId": 0,
                                "buysingle": false,
                                "showStartProId": 0,
                                "needMessage": 0,
                                "message": "",
                                "preSale": 1,
                                "defaultMessage": "",
                                "tax": "13",
                                "albumSaleDisplayType": 0,
                                "restrict": 1,
                                "giftSet": 1
                            },
                            "specialType": 0,
                            "shopId": 36000,
                            "exchangeType": 0,
                            "useVipPrice": false,
                            "statistics": 0,
                            "picUrls": [
                                "http://p4.music.126.net/faqY8g26KlmiuTCU6OLkGQ==/109951164540945896.jpg",
                                "http://p3.music.126.net/4j61fFoXLnrjASPYDlFKTw==/109951164540963201.jpg",
                                "http://p3.music.126.net/PyxMt5Ynd_19FzS0D0xaHQ==/109951164540960499.jpg",
                                "http://p3.music.126.net/vHMNE8Q2tBbStBg8ebf6MQ==/109951164540951818.jpg",
                                "http://p3.music.126.net/185csA4bMtjA8e-Qa6IOZg==/109951164540958095.jpg",
                                "http://p3.music.126.net/r6WkM6UBVRILNTFP7k7pKw==/109951164540962309.jpg",
                                "http://p3.music.126.net/qg75yvESGkGC2OBwN-NFlQ==/109951164540965806.jpg",
                                "http://p3.music.126.net/Yw6WUdwOhN2e1UMpcbCnLQ==/109951164552707706.jpg"
                            ],
                            "coverUrl": "http://p3.music.126.net/Yw6WUdwOhN2e1UMpcbCnLQ==/109951164552707706.jpg",
                            "performanceTime": 0,
                            "coverIdStr": "109951164552707706",
                            "category2": 2026000,
                            "suggestWord": "小巧轻便，令人愉悦的小型乐器",
                            "brandName": "网易云",
                            "alterStock": 0,
                            "iap": false,
                            "tags": [],
                            "display": 0,
                            "status": 0,
                            "name": "【新品预售12月17日发货】网易云音乐易系列17音卡林巴拇指琴 二色可选",
                            "id": 21832613,
                            "type": 2,
                            "minPrice": 288,
                            "originalCost": 288,
                            "maxPrice": 288,
                            "alg": "featured"
                        },
                        "db_update_time": 1576469552000
                    },
                    {
                        "db_create_time": 1576484502596,
                        "id": 10002,
                        "names": "伯朗 i9S蓝牙5.0真无线耳机双耳通话苹果安卓通用",
                        "price": null,
                        "productId": 11703003,
                        "resourceUrl": null,
                        "orderWeight": 6,
                        "products": {
                            "stock": 1419,
                            "saleNum": 0,
                            "sumMoney": null,
                            "skus": null,
                            "discount": null,
                            "pickUp": false,
                            "picIds": [
                                "109951164094159737",
                                "109951164077937291",
                                "109951164077934351",
                                "109951164094153476",
                                "109951164094157304"
                            ],
                            "couponLabelDesc": null,
                            "couponLabelFlag": 0,
                            "label": null,
                            "category1": 101000,
                            "drawTime": 0,
                            "pubTime": 1558059869497,
                            "createTime": 1557996069167,
                            "priceType": 1,
                            "levelLimit": 0,
                            "vipLimit": false,
                            "allowDupBuy": true,
                            "extInfo": {
                                "albumId": 0,
                                "songId": 0,
                                "goodVipType": 11,
                                "quotaOfOrder": 0,
                                "extProductId": 0,
                                "extProductStatus": 0,
                                "extShelfStatus": 0,
                                "concertId": 0,
                                "buysingle": false,
                                "showStartProId": 0,
                                "needMessage": 0,
                                "message": "",
                                "preSale": 1,
                                "defaultMessage": "",
                                "albumSaleDisplayType": 0,
                                "restrict": 1,
                                "giftSet": 1
                            },
                            "specialType": 0,
                            "shopId": 84000,
                            "exchangeType": 0,
                            "useVipPrice": false,
                            "statistics": 6,
                            "picUrls": [
                                "http://p4.music.126.net/eZO47Pir75pgd1eQbY4OVA==/109951164094159737.jpg",
                                "http://p3.music.126.net/JoivF7YdpLKzdFrFYuE5uA==/109951164077937291.jpg",
                                "http://p3.music.126.net/ZdW3E_uAaPQvq2WbHi8fxA==/109951164077934351.jpg",
                                "http://p4.music.126.net/AElthrKJEcJGqSOlcKcBrg==/109951164094153476.jpg",
                                "http://p3.music.126.net/EIuIWTN-0lo6SOrBmHY_ZA==/109951164094157304.jpg"
                            ],
                            "coverUrl": "http://p4.music.126.net/eZO47Pir75pgd1eQbY4OVA==/109951164094159737.jpg",
                            "performanceTime": 0,
                            "coverIdStr": "109951164094159737",
                            "category2": 1005000,
                            "suggestWord": "【赠送硅胶保护套+登山扣】蓝牙5.0 佩戴舒适 自带充电仓便携 双耳通话",
                            "brandName": "伯朗",
                            "alterStock": 0,
                            "iap": false,
                            "tags": [
                                "特价"
                            ],
                            "display": 0,
                            "status": 0,
                            "name": "伯朗 i9S蓝牙5.0真无线耳机双耳通话苹果安卓通用",
                            "id": 11703003,
                            "type": 2,
                            "minPrice": 89,
                            "originalCost": 169,
                            "maxPrice": 89,
                            "alg": "featured"
                        },
                        "db_update_time": 1576469552000
                    },
                    {
                        "db_create_time": 1576484502596,
                        "id": 10007,
                        "names": "兰士顿 D4线控重低音炮四核双动圈耳机 苹果安卓通用 带麦",
                        "price": null,
                        "productId": 17887045,
                        "resourceUrl": null,
                        "orderWeight": 7,
                        "products": {
                            "stock": 3852,
                            "saleNum": 0,
                            "sumMoney": null,
                            "skus": null,
                            "discount": null,
                            "pickUp": false,
                            "picIds": [
                                "109951164205753600",
                                "109951164205747843",
                                "109951164205753140",
                                "109951164205745417"
                            ],
                            "couponLabelDesc": null,
                            "couponLabelFlag": 0,
                            "label": null,
                            "category1": 101000,
                            "drawTime": 0,
                            "pubTime": 1562810263091,
                            "createTime": 1562770736561,
                            "priceType": 1,
                            "levelLimit": 0,
                            "vipLimit": false,
                            "allowDupBuy": true,
                            "extInfo": {
                                "albumId": 0,
                                "songId": 0,
                                "goodVipType": 11,
                                "quotaOfOrder": 0,
                                "extProductId": 0,
                                "extProductStatus": 0,
                                "extShelfStatus": 0,
                                "concertId": 0,
                                "buysingle": false,
                                "showStartProId": 0,
                                "needMessage": 0,
                                "message": "",
                                "preSale": 1,
                                "defaultMessage": "",
                                "albumSaleDisplayType": 0,
                                "restrict": 1,
                                "giftSet": 1
                            },
                            "specialType": 0,
                            "shopId": 84000,
                            "exchangeType": 0,
                            "useVipPrice": false,
                            "statistics": 0,
                            "picUrls": [
                                "http://p4.music.126.net/BWZCBNkmsGHepFgXbz_LGw==/109951164205753600.jpg",
                                "http://p4.music.126.net/-Zks6pBvmIRxsaer1vACrQ==/109951164205747843.jpg",
                                "http://p4.music.126.net/Vh9Bpo-6E3MKLDQIRUBm3w==/109951164205753140.jpg",
                                "http://p3.music.126.net/WA7pMuve6IlN1yAczhD6FA==/109951164205745417.jpg"
                            ],
                            "coverUrl": "http://p4.music.126.net/BWZCBNkmsGHepFgXbz_LGw==/109951164205753600.jpg",
                            "performanceTime": 0,
                            "coverIdStr": "109951164205753600",
                            "category2": 1005000,
                            "suggestWord": "4核驱动 4个喇叭  震撼重低音  纯正音质 苹果安卓通用 线控带麦",
                            "brandName": "兰士顿",
                            "alterStock": 0,
                            "iap": false,
                            "tags": [
                                "特价"
                            ],
                            "display": 0,
                            "status": 0,
                            "name": "兰士顿 D4线控重低音炮四核双动圈耳机 苹果安卓通用 带麦",
                            "id": 17887045,
                            "type": 2,
                            "minPrice": 99,
                            "originalCost": 159,
                            "maxPrice": 109,
                            "alg": "featured"
                        },
                        "db_update_time": 1576469552000
                    },
                    {
                        "db_create_time": 1576484502596,
                        "id": 10005,
                        "names": "网易云音乐简约声波电动牙刷",
                        "price": null,
                        "productId": 18073000,
                        "resourceUrl": null,
                        "orderWeight": 8,
                        "products": {
                            "stock": 1764,
                            "saleNum": 0,
                            "sumMoney": null,
                            "skus": null,
                            "discount": null,
                            "pickUp": false,
                            "picIds": [
                                "109951164298104543",
                                "109951164298092952",
                                "109951164298092466",
                                "109951164298092467",
                                "109951164298097751",
                                "109951164298122310",
                                "109951164298125204"
                            ],
                            "couponLabelDesc": null,
                            "couponLabelFlag": 0,
                            "label": "",
                            "category1": 1005001,
                            "drawTime": 0,
                            "pubTime": 1571135979416,
                            "createTime": 1565935147927,
                            "priceType": 1,
                            "levelLimit": 0,
                            "vipLimit": false,
                            "allowDupBuy": true,
                            "extInfo": {
                                "albumId": 0,
                                "songId": 0,
                                "goodVipType": 0,
                                "quotaOfOrder": 0,
                                "extProductId": 0,
                                "extProductStatus": 0,
                                "extShelfStatus": 0,
                                "concertId": 0,
                                "buysingle": false,
                                "showStartProId": 0,
                                "needMessage": 0,
                                "preSale": 1,
                                "defaultMessage": "",
                                "albumSaleDisplayType": 0,
                                "restrict": 1,
                                "giftSet": 0
                            },
                            "specialType": 0,
                            "shopId": 0,
                            "exchangeType": 0,
                            "useVipPrice": false,
                            "statistics": 0,
                            "picUrls": [
                                "http://p4.music.126.net/J-4Xq6-QwXW-u4NuA4XtBg==/109951164298104543.jpg",
                                "http://p4.music.126.net/YXql8GSkMuSZqvP3H24G3A==/109951164298092952.jpg",
                                "http://p4.music.126.net/vZcqYOL8uI_ffpUpeBvIwA==/109951164298092466.jpg",
                                "http://p3.music.126.net/cDGzj6ntx5dPd4KNuSEtJw==/109951164298092467.jpg",
                                "http://p4.music.126.net/ALdNHIHUi588IdnWDBchMA==/109951164298097751.jpg",
                                "http://p4.music.126.net/YOxAktYt4IJUOkCRfH756Q==/109951164298122310.jpg",
                                "http://p3.music.126.net/IZaqW7C628Ro5cvRuf1NoA==/109951164298125204.jpg"
                            ],
                            "coverUrl": "http://p4.music.126.net/YOxAktYt4IJUOkCRfH756Q==/109951164298122310.jpg",
                            "performanceTime": 0,
                            "coverIdStr": "109951164298122310",
                            "category2": 1006002,
                            "suggestWord": "健齿护龈好帮手，深层清洁让牙齿问题远离你！",
                            "brandName": "网易云音乐",
                            "alterStock": 0,
                            "iap": false,
                            "tags": [
                                "特价"
                            ],
                            "display": 0,
                            "status": 0,
                            "name": "网易云音乐简约声波电动牙刷",
                            "id": 18073000,
                            "type": 2,
                            "minPrice": 29,
                            "originalCost": 69,
                            "maxPrice": 119,
                            "alg": "featured"
                        },
                        "db_update_time": 1576469552000
                    }
                ]
            }
        };
    }
    componentDidMount() {
        console.log(this.state.RecommendData.hotProduct)
    }
    render() {
        return (
            <div className="RecommendBox">
                <div className="RecommendTitle">编辑推荐</div>
                {this.state.RecommendData.hotProduct.map((item, index) => {
                    return (
                        <div className="RecommendLiBox" key={index}>
                            <div className="oldPayBox">
                                <p className="newPay">¥{item.products.minPrice}</p>
                                <p className="oldPay">¥{item.products.originalCost}</p>
                            </div>
                            <img src={item.products.coverUrl} className="RecommendBoxImg"></img>
                            <div className="RecommendBoxTtitle">{item.products.tags[0] && <span className="tag">{item.products.tags[0]}</span>}{item.names}</div>
                            <p className="RecommendPay">¥{item.products.maxPrice}</p>
                        </div>
                    )
                })}
                <div className="digalb">
                <div className="inner">
                    <div className="innerBox">
                        <span className="innerIcon"></span>
                        <span className="innerTxt">数字专辑</span>
                        <p className="innerTxt2">Taylor Swift 新专辑火热售卖中</p>
                        <a className="innerTxt3">立 即 购 买 ></a>
                        </div>
                    </div>
                    
                    <div className="covers">
                        <img src="https://p1.music.126.net/D1gL45hPNWNxoq1Foanh6Q==/109951164370176967.jpg?param=120y120" className="coversImg1"></img>
                        <img src="https://p2.music.126.net/6CB6Jsmb7k7qiJqfMY5Row==/109951164260234943.jpg?param=120y120" className="coversImg2"></img>
                        <i className="coverIcon"></i>
                    </div>
                </div>
            </div>
        );
    }
}

export default Recommend;